# Generated by Django 5.0.6 on 2024-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='started_date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
