# Generated by Django 5.0.6 on 2024-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_education_date_remove_experience_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='bio',
            field=models.TextField(max_length=600),
        ),
    ]
