# Generated by Django 4.2.7 on 2024-06-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_index_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image',
        ),
    ]
