# Generated by Django 4.2.7 on 2024-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_index_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_date',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
