# Generated by Django 4.2.7 on 2024-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
