# Generated by Django 4.2.7 on 2024-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_education_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
